### PR TITLE
Created GH Actions files

### PR DESCRIPTION
**Pull request by PatStLouis**
Dependabot, chart publisher, container image publisher

### CODE REVIEW

**Review by esune — COMMENTED** [review]
You may be able to just reference the Helm releaser action (see [here](https://github.com/helm/chart-releaser-action?tab=readme-ov-file#example-workflow)) rather than have its definition in the repo. I forget why we cloned it in our `bcgov` repos, checking with @i5okie about it

**Review by esune — CHANGES_REQUESTED** [review]
Confirmed we should be able to just reference the published action, I would suggest we switch to using that so we have less code to directly care for

**Comment by PatStLouis** [comment]
@esune I've implemented your suggestion

**Review by esune — APPROVED** [review]
I think this looks good. Can try and trigger it when merged so the latest chart is published and try using it now.

**Pull request merged**
